apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-monitoring-config
  namespace: openshift-monitoring
data:
  config.yaml: |
    telemeterClient:
      telemeterServerURL: https://infogw.api.stage.openshift.com
      token: b3BlbnNoaWZ0LXJlbGVhc2UtZGV2K2p1emhhb3JlZGhhdGNvbTFkdTFjZWdrcGppd2J0d2o4eXZ6MWtsd3hmZzpYQkUxTTc4TDE5VEs3S1czTlY0NkNDTkVTSENJS1FVUTNPN01JVkJQV1U1NUdTMjRJQzA4RlBBUDVaM1VBQ1BB
    enableUserWorkload: true
